### ISSUE TITLE
せっかく登壇したのだから登壇資料のリンクを貼った方がよいと思う。

### ISSUE THREAD

**Issue by Ippey** [ktkn1129/about_tiger#2]
JAWS FESTAでLTやって２位、３位すげー！なので、
登壇資料が見れるようにリンクを貼った方がよいと思いました。
その他諸々、資料や作品を公開してるなら積極的に見せた方が良いかなーと思います。

**Comment by ktkn1129** [comment]
@ippey 確かにそうですね！
訂正します！ありがとうございます！

**Comment by ktkn1129** [comment]
@Ippey 追加させていただきました〜！クローズします！対応遅くてすみませんでした！
Ippeyさんがレビュワーで追加できなかったのってなんでなのでしょう…:thinking:(追加できなかったので、諦めてしれっとマージしました・・・:pray:)
